
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace JobsInABA.DAL.Entities
{

using System;
    using System.Collections.Generic;
    
public partial class Achievement
{

    public int AchievementID { get; set; }

    public string Name { get; set; }

    public Nullable<System.DateTime> Date { get; set; }

    public Nullable<int> UserID { get; set; }

    public Nullable<int> BusinessID { get; set; }



    public virtual Business Business { get; set; }

    public virtual User User { get; set; }

}

}
