
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace JobsInABA.DAL.Entities
{

using System;
    using System.Collections.Generic;
    
public partial class BusinessImage
{

    public int BusinessImageID { get; set; }

    public int BusinessID { get; set; }

    public int ImageID { get; set; }

    public bool IsPrimary { get; set; }



    public virtual Business Business { get; set; }

    public virtual Image Image { get; set; }

}

}
