
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace JobsInABA.DAL.Entities
{

using System;
    using System.Collections.Generic;
    
public partial class BusinessAddress
{

    public int BusinessAddressID { get; set; }

    public int BusinessID { get; set; }

    public int AddressID { get; set; }

    public bool IsPrimary { get; set; }



    public virtual Address Address { get; set; }

    public virtual Business Business { get; set; }

}

}
