
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace JobsInABA.DAL.Entities
{

using System;
    using System.Collections.Generic;
    
public partial class Business
{

    public Business()
    {

        this.Achievements = new HashSet<Achievement>();

        this.BusinessAddresses = new HashSet<BusinessAddress>();

        this.BusinessEmails = new HashSet<BusinessEmail>();

        this.BusinessImages = new HashSet<BusinessImage>();

        this.BusinessPhones = new HashSet<BusinessPhone>();

        this.BusinessUserMaps = new HashSet<BusinessUserMap>();

        this.Experiences = new HashSet<Experience>();

        this.Jobs = new HashSet<Job>();

        this.Services = new HashSet<Service>();

    }


    public int BusinessID { get; set; }

    public string Name { get; set; }

    public string Abbreviation { get; set; }

    public Nullable<System.DateTime> StartDate { get; set; }

    public string Description { get; set; }

    public int BusinessTypeID { get; set; }

    public bool IsActive { get; set; }

    public bool IsDeleted { get; set; }

    public Nullable<int> insuser { get; set; }

    public Nullable<System.DateTime> insdt { get; set; }

    public Nullable<int> upduser { get; set; }

    public Nullable<System.DateTime> upddt { get; set; }



    public virtual ICollection<Achievement> Achievements { get; set; }

    public virtual ICollection<BusinessAddress> BusinessAddresses { get; set; }

    public virtual ICollection<BusinessEmail> BusinessEmails { get; set; }

    public virtual TypeCode TypeCode { get; set; }

    public virtual User User { get; set; }

    public virtual User User1 { get; set; }

    public virtual ICollection<BusinessImage> BusinessImages { get; set; }

    public virtual ICollection<BusinessPhone> BusinessPhones { get; set; }

    public virtual ICollection<BusinessUserMap> BusinessUserMaps { get; set; }

    public virtual ICollection<Experience> Experiences { get; set; }

    public virtual ICollection<Job> Jobs { get; set; }

    public virtual ICollection<Service> Services { get; set; }

}

}
