
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace JobsInABA.DAL.Entities
{

using System;
    using System.Collections.Generic;
    
public partial class BusinessUserMap
{

    public int BusinessUserMapID { get; set; }

    public int BusinessID { get; set; }

    public int UserID { get; set; }

    public bool IsOwner { get; set; }

    public Nullable<int> BusinessUserTypeID { get; set; }



    public virtual Business Business { get; set; }

    public virtual TypeCode TypeCode { get; set; }

    public virtual User User { get; set; }

}

}
