
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace JobsInABA.DAL.Entities
{

using System;
    using System.Collections.Generic;
    
public partial class Country
{

    public Country()
    {

        this.Addresses = new HashSet<Address>();

    }


    public int CountryID { get; set; }

    public string Name { get; set; }

    public string Abbreviation { get; set; }

    public string Code { get; set; }

    public string PhoneCode { get; set; }



    public virtual ICollection<Address> Addresses { get; set; }

}

}
