
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace JobsInABA.DAL.Entities
{

using System;
    using System.Collections.Generic;
    
public partial class Email
{

    public Email()
    {

        this.BusinessEmails = new HashSet<BusinessEmail>();

        this.UserEmails = new HashSet<UserEmail>();

    }


    public int EmailID { get; set; }

    public string Address { get; set; }

    public Nullable<int> EmailTypeID { get; set; }



    public virtual ICollection<BusinessEmail> BusinessEmails { get; set; }

    public virtual TypeCode TypeCode { get; set; }

    public virtual ICollection<UserEmail> UserEmails { get; set; }

}

}
