
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace JobsInABA.DAL.Entities
{

using System;
    using System.Collections.Generic;
    
public partial class Image
{

    public Image()
    {

        this.BusinessImages = new HashSet<BusinessImage>();

        this.UserImages = new HashSet<UserImage>();

    }


    public int ImageID { get; set; }

    public string Name { get; set; }

    public int ImageTypeID { get; set; }

    public string ImageExtension { get; set; }



    public virtual ICollection<BusinessImage> BusinessImages { get; set; }

    public virtual TypeCode TypeCode { get; set; }

    public virtual ICollection<UserImage> UserImages { get; set; }

}

}
