
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace JobsInABA.DAL.Entities
{

using System;
    using System.Collections.Generic;
    
public partial class JobApplicationState
{

    public int JobApplicationStateID { get; set; }

    public int JobApplicationID { get; set; }

    public int JobApplicationStatusID { get; set; }

    public System.DateTime insdt { get; set; }

    public int insuser { get; set; }



    public virtual JobApplication JobApplication { get; set; }

    public virtual TypeCode TypeCode { get; set; }

}

}
