
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace JobsInABA.DAL.Entities
{

using System;
    using System.Collections.Generic;
    
public partial class TypeCode
{

    public TypeCode()
    {

        this.Addresses = new HashSet<Address>();

        this.Businesses = new HashSet<Business>();

        this.BusinessUserMaps = new HashSet<BusinessUserMap>();

        this.Emails = new HashSet<Email>();

        this.Images = new HashSet<Image>();

        this.JobApplicationStates = new HashSet<JobApplicationState>();

        this.Jobs = new HashSet<Job>();

        this.Phones = new HashSet<Phone>();

        this.TypeCodes1 = new HashSet<TypeCode>();

    }


    public int TypeCodeID { get; set; }

    public string Name { get; set; }

    public string Code { get; set; }

    public string Description { get; set; }

    public int ClassTypeID { get; set; }

    public Nullable<int> ParentTypeCodeID { get; set; }



    public virtual ICollection<Address> Addresses { get; set; }

    public virtual ICollection<Business> Businesses { get; set; }

    public virtual ICollection<BusinessUserMap> BusinessUserMaps { get; set; }

    public virtual ClassType ClassType { get; set; }

    public virtual ICollection<Email> Emails { get; set; }

    public virtual ICollection<Image> Images { get; set; }

    public virtual ICollection<JobApplicationState> JobApplicationStates { get; set; }

    public virtual ICollection<Job> Jobs { get; set; }

    public virtual ICollection<Phone> Phones { get; set; }

    public virtual ICollection<TypeCode> TypeCodes1 { get; set; }

    public virtual TypeCode TypeCode1 { get; set; }

}

}
