
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace JobsInABA.DAL.Entities
{

using System;
    using System.Collections.Generic;
    
public partial class UserAccount
{

    public int UserAccountID { get; set; }

    public int UserID { get; set; }

    public string UserName { get; set; }

    public byte[] Password { get; set; }

    public bool IsActive { get; set; }

    public bool IsDeleted { get; set; }

    public Nullable<int> insuser { get; set; }

    public Nullable<System.DateTime> insdt { get; set; }

    public Nullable<int> upduser { get; set; }

    public Nullable<System.DateTime> upddt { get; set; }



    public virtual User User { get; set; }

}

}
