
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace JobsInABA.DAL.Entities
{

using System;
    using System.Collections.Generic;
    
public partial class User
{

    public User()
    {

        this.Achievements = new HashSet<Achievement>();

        this.Businesses = new HashSet<Business>();

        this.Businesses1 = new HashSet<Business>();

        this.BusinessUserMaps = new HashSet<BusinessUserMap>();

        this.Educations = new HashSet<Education>();

        this.Experiences = new HashSet<Experience>();

        this.JobApplications = new HashSet<JobApplication>();

        this.Languages = new HashSet<Language>();

        this.Skills = new HashSet<Skill>();

        this.UserAccounts = new HashSet<UserAccount>();

        this.UserAddresses = new HashSet<UserAddress>();

        this.UserEmails = new HashSet<UserEmail>();

        this.UserImages = new HashSet<UserImage>();

        this.UserPhones = new HashSet<UserPhone>();

        this.UserRoles = new HashSet<UserRole>();

        this.Users1 = new HashSet<User>();

        this.Users11 = new HashSet<User>();

        this.JobApplications1 = new HashSet<JobApplication>();

    }


    public int UserID { get; set; }

    public string UserName { get; set; }

    public string FirstName { get; set; }

    public string MiddleName { get; set; }

    public string LastName { get; set; }

    public Nullable<System.DateTime> DOB { get; set; }

    public bool IsActive { get; set; }

    public bool IsDeleted { get; set; }

    public Nullable<int> insuser { get; set; }

    public Nullable<System.DateTime> insdt { get; set; }

    public Nullable<int> upduser { get; set; }

    public Nullable<System.DateTime> upddt { get; set; }

    public string Description { get; set; }



    public virtual ICollection<Achievement> Achievements { get; set; }

    public virtual ICollection<Business> Businesses { get; set; }

    public virtual ICollection<Business> Businesses1 { get; set; }

    public virtual ICollection<BusinessUserMap> BusinessUserMaps { get; set; }

    public virtual ICollection<Education> Educations { get; set; }

    public virtual ICollection<Experience> Experiences { get; set; }

    public virtual ICollection<JobApplication> JobApplications { get; set; }

    public virtual ICollection<Language> Languages { get; set; }

    public virtual ICollection<Skill> Skills { get; set; }

    public virtual ICollection<UserAccount> UserAccounts { get; set; }

    public virtual ICollection<UserAddress> UserAddresses { get; set; }

    public virtual ICollection<UserEmail> UserEmails { get; set; }

    public virtual ICollection<UserImage> UserImages { get; set; }

    public virtual ICollection<UserPhone> UserPhones { get; set; }

    public virtual ICollection<UserRole> UserRoles { get; set; }

    public virtual ICollection<User> Users1 { get; set; }

    public virtual User User1 { get; set; }

    public virtual ICollection<User> Users11 { get; set; }

    public virtual User User2 { get; set; }

    public virtual ICollection<JobApplication> JobApplications1 { get; set; }

}

}
