//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.2 (entitiestodtos.codeplex.com).
//     Timestamp: 2016/02/22 - 20:58:46
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;
using System.Linq;
using JobsInABA.BL.DTOs;
using JobsInABA.DAL.Entities;

namespace JobsInABA.BL.DTOs.Assemblers
{

    /// <summary>
    /// Assembler for <see cref="Business"/> and <see cref="BusinessDTO"/>.
    /// </summary>
    public static partial class BusinessAssembler
    {
        /// <summary>
        /// Invoked when <see cref="ToDTO"/> operation is about to return.
        /// </summary>
        /// <param name="dto"><see cref="BusinessDTO"/> converted from <see cref="Business"/>.</param>
        static partial void OnDTO(this Business entity, BusinessDTO dto);

        /// <summary>
        /// Invoked when <see cref="ToEntity"/> operation is about to return.
        /// </summary>
        /// <param name="entity"><see cref="Business"/> converted from <see cref="BusinessDTO"/>.</param>
        static partial void OnEntity(this BusinessDTO dto, Business entity);

        /// <summary>
        /// Converts this instance of <see cref="BusinessDTO"/> to an instance of <see cref="Business"/>.
        /// </summary>
        /// <param name="dto"><see cref="BusinessDTO"/> to convert.</param>
        public static Business ToEntity(this BusinessDTO dto)
        {
            if (dto == null) return null;

            var entity = new Business();

            entity.BusinessID = dto.BusinessID;
            entity.Name = dto.Name;
            entity.Abbreviation = dto.Abbreviation;
            entity.StartDate = dto.StartDate;
            entity.Description = dto.Description;
            entity.BusinessTypeID = dto.BusinessTypeID;
            entity.IsActive = dto.IsActive;
            entity.IsDeleted = dto.IsDeleted;
            entity.insuser = dto.insuser;
            entity.insdt = dto.insdt;
            entity.upduser = dto.upduser;
            entity.upddt = dto.upddt;

            dto.OnEntity(entity);

            return entity;
        }

        /// <summary>
        /// Converts this instance of <see cref="Business"/> to an instance of <see cref="BusinessDTO"/>.
        /// </summary>
        /// <param name="entity"><see cref="Business"/> to convert.</param>
        public static BusinessDTO ToDTO(this Business entity)
        {
            if (entity == null) return null;

            var dto = new BusinessDTO();

            dto.BusinessID = entity.BusinessID;
            dto.Name = entity.Name;
            dto.Abbreviation = entity.Abbreviation;
            dto.StartDate = entity.StartDate;
            dto.Description = entity.Description;
            dto.BusinessTypeID = entity.BusinessTypeID;
            dto.IsActive = entity.IsActive;
            dto.IsDeleted = entity.IsDeleted;
            dto.insuser = entity.insuser;
            dto.insdt = entity.insdt;
            dto.upduser = entity.upduser;
            dto.upddt = entity.upddt;

            entity.OnDTO(dto);

            return dto;
        }

        /// <summary>
        /// Converts each instance of <see cref="BusinessDTO"/> to an instance of <see cref="Business"/>.
        /// </summary>
        /// <param name="dtos"></param>
        /// <returns></returns>
        public static List<Business> ToEntities(this IEnumerable<BusinessDTO> dtos)
        {
            if (dtos == null) return null;

            return dtos.Select(e => e.ToEntity()).ToList();
        }

        /// <summary>
        /// Converts each instance of <see cref="Business"/> to an instance of <see cref="BusinessDTO"/>.
        /// </summary>
        /// <param name="entities"></param>
        /// <returns></returns>
        public static List<BusinessDTO> ToDTOs(this IEnumerable<Business> entities)
        {
            if (entities == null) return null;

            return entities.Select(e => e.ToDTO()).ToList();
        }

    }
}
