//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.2 (entitiestodtos.codeplex.com).
//     Timestamp: 2016/02/22 - 20:58:46
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;
using System.Linq;
using JobsInABA.BL.DTOs;
using JobsInABA.DAL.Entities;

namespace JobsInABA.BL.DTOs.Assemblers
{

    /// <summary>
    /// Assembler for <see cref="BusinessPhone"/> and <see cref="BusinessPhoneDTO"/>.
    /// </summary>
    public static partial class BusinessPhoneAssembler
    {
        /// <summary>
        /// Invoked when <see cref="ToDTO"/> operation is about to return.
        /// </summary>
        /// <param name="dto"><see cref="BusinessPhoneDTO"/> converted from <see cref="BusinessPhone"/>.</param>
        static partial void OnDTO(this BusinessPhone entity, BusinessPhoneDTO dto);

        /// <summary>
        /// Invoked when <see cref="ToEntity"/> operation is about to return.
        /// </summary>
        /// <param name="entity"><see cref="BusinessPhone"/> converted from <see cref="BusinessPhoneDTO"/>.</param>
        static partial void OnEntity(this BusinessPhoneDTO dto, BusinessPhone entity);

        /// <summary>
        /// Converts this instance of <see cref="BusinessPhoneDTO"/> to an instance of <see cref="BusinessPhone"/>.
        /// </summary>
        /// <param name="dto"><see cref="BusinessPhoneDTO"/> to convert.</param>
        public static BusinessPhone ToEntity(this BusinessPhoneDTO dto)
        {
            if (dto == null) return null;

            var entity = new BusinessPhone();

            entity.BusinessPhoneID = dto.BusinessPhoneID;
            entity.BusinessID = dto.BusinessID;
            entity.PhoneID = dto.PhoneID;
            entity.IsPrimary = dto.IsPrimary;

            dto.OnEntity(entity);

            return entity;
        }

        /// <summary>
        /// Converts this instance of <see cref="BusinessPhone"/> to an instance of <see cref="BusinessPhoneDTO"/>.
        /// </summary>
        /// <param name="entity"><see cref="BusinessPhone"/> to convert.</param>
        public static BusinessPhoneDTO ToDTO(this BusinessPhone entity)
        {
            if (entity == null) return null;

            var dto = new BusinessPhoneDTO();

            dto.BusinessPhoneID = entity.BusinessPhoneID;
            dto.BusinessID = entity.BusinessID;
            dto.PhoneID = entity.PhoneID;
            dto.IsPrimary = entity.IsPrimary;

            entity.OnDTO(dto);

            return dto;
        }

        /// <summary>
        /// Converts each instance of <see cref="BusinessPhoneDTO"/> to an instance of <see cref="BusinessPhone"/>.
        /// </summary>
        /// <param name="dtos"></param>
        /// <returns></returns>
        public static List<BusinessPhone> ToEntities(this IEnumerable<BusinessPhoneDTO> dtos)
        {
            if (dtos == null) return null;

            return dtos.Select(e => e.ToEntity()).ToList();
        }

        /// <summary>
        /// Converts each instance of <see cref="BusinessPhone"/> to an instance of <see cref="BusinessPhoneDTO"/>.
        /// </summary>
        /// <param name="entities"></param>
        /// <returns></returns>
        public static List<BusinessPhoneDTO> ToDTOs(this IEnumerable<BusinessPhone> entities)
        {
            if (entities == null) return null;

            return entities.Select(e => e.ToDTO()).ToList();
        }

    }
}
