//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.2 (entitiestodtos.codeplex.com).
//     Timestamp: 2016/02/22 - 20:58:46
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;
using System.Linq;
using JobsInABA.BL.DTOs;
using JobsInABA.DAL.Entities;

namespace JobsInABA.BL.DTOs.Assemblers
{

    /// <summary>
    /// Assembler for <see cref="BusinessImage"/> and <see cref="BusinessImageDTO"/>.
    /// </summary>
    public static partial class BusinessImageAssembler
    {
        /// <summary>
        /// Invoked when <see cref="ToDTO"/> operation is about to return.
        /// </summary>
        /// <param name="dto"><see cref="BusinessImageDTO"/> converted from <see cref="BusinessImage"/>.</param>
        static partial void OnDTO(this BusinessImage entity, BusinessImageDTO dto);

        /// <summary>
        /// Invoked when <see cref="ToEntity"/> operation is about to return.
        /// </summary>
        /// <param name="entity"><see cref="BusinessImage"/> converted from <see cref="BusinessImageDTO"/>.</param>
        static partial void OnEntity(this BusinessImageDTO dto, BusinessImage entity);

        /// <summary>
        /// Converts this instance of <see cref="BusinessImageDTO"/> to an instance of <see cref="BusinessImage"/>.
        /// </summary>
        /// <param name="dto"><see cref="BusinessImageDTO"/> to convert.</param>
        public static BusinessImage ToEntity(this BusinessImageDTO dto)
        {
            if (dto == null) return null;

            var entity = new BusinessImage();

            entity.BusinessImageID = dto.BusinessImageID;
            entity.BusinessID = dto.BusinessID;
            entity.ImageID = dto.ImageID;
            entity.IsPrimary = dto.IsPrimary;

            dto.OnEntity(entity);

            return entity;
        }

        /// <summary>
        /// Converts this instance of <see cref="BusinessImage"/> to an instance of <see cref="BusinessImageDTO"/>.
        /// </summary>
        /// <param name="entity"><see cref="BusinessImage"/> to convert.</param>
        public static BusinessImageDTO ToDTO(this BusinessImage entity)
        {
            if (entity == null) return null;

            var dto = new BusinessImageDTO();

            dto.BusinessImageID = entity.BusinessImageID;
            dto.BusinessID = entity.BusinessID;
            dto.ImageID = entity.ImageID;
            dto.IsPrimary = entity.IsPrimary;

            entity.OnDTO(dto);

            return dto;
        }

        /// <summary>
        /// Converts each instance of <see cref="BusinessImageDTO"/> to an instance of <see cref="BusinessImage"/>.
        /// </summary>
        /// <param name="dtos"></param>
        /// <returns></returns>
        public static List<BusinessImage> ToEntities(this IEnumerable<BusinessImageDTO> dtos)
        {
            if (dtos == null) return null;

            return dtos.Select(e => e.ToEntity()).ToList();
        }

        /// <summary>
        /// Converts each instance of <see cref="BusinessImage"/> to an instance of <see cref="BusinessImageDTO"/>.
        /// </summary>
        /// <param name="entities"></param>
        /// <returns></returns>
        public static List<BusinessImageDTO> ToDTOs(this IEnumerable<BusinessImage> entities)
        {
            if (entities == null) return null;

            return entities.Select(e => e.ToDTO()).ToList();
        }

    }
}
