//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.2 (entitiestodtos.codeplex.com).
//     Timestamp: 2016/02/22 - 20:58:45
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;
using System.Linq;
using JobsInABA.BL.DTOs;
using JobsInABA.DAL.Entities;

namespace JobsInABA.BL.DTOs.Assemblers
{

    /// <summary>
    /// Assembler for <see cref="BusinessAddress"/> and <see cref="BusinessAddressDTO"/>.
    /// </summary>
    public static partial class BusinessAddressAssembler
    {
        /// <summary>
        /// Invoked when <see cref="ToDTO"/> operation is about to return.
        /// </summary>
        /// <param name="dto"><see cref="BusinessAddressDTO"/> converted from <see cref="BusinessAddress"/>.</param>
        static partial void OnDTO(this BusinessAddress entity, BusinessAddressDTO dto);

        /// <summary>
        /// Invoked when <see cref="ToEntity"/> operation is about to return.
        /// </summary>
        /// <param name="entity"><see cref="BusinessAddress"/> converted from <see cref="BusinessAddressDTO"/>.</param>
        static partial void OnEntity(this BusinessAddressDTO dto, BusinessAddress entity);

        /// <summary>
        /// Converts this instance of <see cref="BusinessAddressDTO"/> to an instance of <see cref="BusinessAddress"/>.
        /// </summary>
        /// <param name="dto"><see cref="BusinessAddressDTO"/> to convert.</param>
        public static BusinessAddress ToEntity(this BusinessAddressDTO dto)
        {
            if (dto == null) return null;

            var entity = new BusinessAddress();

            entity.BusinessAddressID = dto.BusinessAddressID;
            entity.BusinessID = dto.BusinessID;
            entity.AddressID = dto.AddressID;
            entity.IsPrimary = dto.IsPrimary;

            dto.OnEntity(entity);

            return entity;
        }

        /// <summary>
        /// Converts this instance of <see cref="BusinessAddress"/> to an instance of <see cref="BusinessAddressDTO"/>.
        /// </summary>
        /// <param name="entity"><see cref="BusinessAddress"/> to convert.</param>
        public static BusinessAddressDTO ToDTO(this BusinessAddress entity)
        {
            if (entity == null) return null;

            var dto = new BusinessAddressDTO();
            //entity.Address.
            dto.BusinessAddressID = entity.BusinessAddressID;
            dto.BusinessID = entity.BusinessID;
            dto.AddressID = entity.AddressID;
            dto.IsPrimary = entity.IsPrimary;

            entity.OnDTO(dto);

            return dto;
        }

        /// <summary>
        /// Converts each instance of <see cref="BusinessAddressDTO"/> to an instance of <see cref="BusinessAddress"/>.
        /// </summary>
        /// <param name="dtos"></param>
        /// <returns></returns>
        public static List<BusinessAddress> ToEntities(this IEnumerable<BusinessAddressDTO> dtos)
        {
            if (dtos == null) return null;

            return dtos.Select(e => e.ToEntity()).ToList();
        }

        /// <summary>
        /// Converts each instance of <see cref="BusinessAddress"/> to an instance of <see cref="BusinessAddressDTO"/>.
        /// </summary>
        /// <param name="entities"></param>
        /// <returns></returns>
        public static List<BusinessAddressDTO> ToDTOs(this IEnumerable<BusinessAddress> entities)
        {
            if (entities == null) return null;

            return entities.Select(e => e.ToDTO()).ToList();
        }

    }
}
