//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.2 (entitiestodtos.codeplex.com).
//     Timestamp: 2016/02/22 - 20:58:46
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;
using System.Linq;
using JobsInABA.BL.DTOs;
using JobsInABA.DAL.Entities;

namespace JobsInABA.BL.DTOs.Assemblers
{

    /// <summary>
    /// Assembler for <see cref="ClassType"/> and <see cref="ClassTypeDTO"/>.
    /// </summary>
    public static partial class ClassTypeAssembler
    {
        /// <summary>
        /// Invoked when <see cref="ToDTO"/> operation is about to return.
        /// </summary>
        /// <param name="dto"><see cref="ClassTypeDTO"/> converted from <see cref="ClassType"/>.</param>
        static partial void OnDTO(this ClassType entity, ClassTypeDTO dto);

        /// <summary>
        /// Invoked when <see cref="ToEntity"/> operation is about to return.
        /// </summary>
        /// <param name="entity"><see cref="ClassType"/> converted from <see cref="ClassTypeDTO"/>.</param>
        static partial void OnEntity(this ClassTypeDTO dto, ClassType entity);

        /// <summary>
        /// Converts this instance of <see cref="ClassTypeDTO"/> to an instance of <see cref="ClassType"/>.
        /// </summary>
        /// <param name="dto"><see cref="ClassTypeDTO"/> to convert.</param>
        public static ClassType ToEntity(this ClassTypeDTO dto)
        {
            if (dto == null) return null;

            var entity = new ClassType();

            entity.ClassTypeID = dto.ClassTypeID;
            entity.Name = dto.Name;
            entity.Code = dto.Code;
            entity.Description = dto.Description;

            dto.OnEntity(entity);

            return entity;
        }

        /// <summary>
        /// Converts this instance of <see cref="ClassType"/> to an instance of <see cref="ClassTypeDTO"/>.
        /// </summary>
        /// <param name="entity"><see cref="ClassType"/> to convert.</param>
        public static ClassTypeDTO ToDTO(this ClassType entity)
        {
            if (entity == null) return null;

            var dto = new ClassTypeDTO();

            dto.ClassTypeID = entity.ClassTypeID;
            dto.Name = entity.Name;
            dto.Code = entity.Code;
            dto.Description = entity.Description;

            entity.OnDTO(dto);

            return dto;
        }

        /// <summary>
        /// Converts each instance of <see cref="ClassTypeDTO"/> to an instance of <see cref="ClassType"/>.
        /// </summary>
        /// <param name="dtos"></param>
        /// <returns></returns>
        public static List<ClassType> ToEntities(this IEnumerable<ClassTypeDTO> dtos)
        {
            if (dtos == null) return null;

            return dtos.Select(e => e.ToEntity()).ToList();
        }

        /// <summary>
        /// Converts each instance of <see cref="ClassType"/> to an instance of <see cref="ClassTypeDTO"/>.
        /// </summary>
        /// <param name="entities"></param>
        /// <returns></returns>
        public static List<ClassTypeDTO> ToDTOs(this IEnumerable<ClassType> entities)
        {
            if (entities == null) return null;

            return entities.Select(e => e.ToDTO()).ToList();
        }

    }
}
