//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.2 (entitiestodtos.codeplex.com).
//     Timestamp: 2016/02/22 - 20:58:46
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;
using System.Linq;
using JobsInABA.BL.DTOs;
using JobsInABA.DAL.Entities;

namespace JobsInABA.BL.DTOs.Assemblers
{

    /// <summary>
    /// Assembler for <see cref="Country"/> and <see cref="CountryDTO"/>.
    /// </summary>
    public static partial class CountryAssembler
    {
        /// <summary>
        /// Invoked when <see cref="ToDTO"/> operation is about to return.
        /// </summary>
        /// <param name="dto"><see cref="CountryDTO"/> converted from <see cref="Country"/>.</param>
        static partial void OnDTO(this Country entity, CountryDTO dto);

        /// <summary>
        /// Invoked when <see cref="ToEntity"/> operation is about to return.
        /// </summary>
        /// <param name="entity"><see cref="Country"/> converted from <see cref="CountryDTO"/>.</param>
        static partial void OnEntity(this CountryDTO dto, Country entity);

        /// <summary>
        /// Converts this instance of <see cref="CountryDTO"/> to an instance of <see cref="Country"/>.
        /// </summary>
        /// <param name="dto"><see cref="CountryDTO"/> to convert.</param>
        public static Country ToEntity(this CountryDTO dto)
        {
            if (dto == null) return null;

            var entity = new Country();

            entity.CountryID = dto.CountryID;
            entity.Name = dto.Name;
            entity.Abbreviation = dto.Abbreviation;
            entity.Code = dto.Code;
            entity.PhoneCode = dto.PhoneCode;

            dto.OnEntity(entity);

            return entity;
        }

        /// <summary>
        /// Converts this instance of <see cref="Country"/> to an instance of <see cref="CountryDTO"/>.
        /// </summary>
        /// <param name="entity"><see cref="Country"/> to convert.</param>
        public static CountryDTO ToDTO(this Country entity)
        {
            if (entity == null) return null;

            var dto = new CountryDTO();

            dto.CountryID = entity.CountryID;
            dto.Name = entity.Name;
            dto.Abbreviation = entity.Abbreviation;
            dto.Code = entity.Code;
            dto.PhoneCode = entity.PhoneCode;

            entity.OnDTO(dto);

            return dto;
        }

        /// <summary>
        /// Converts each instance of <see cref="CountryDTO"/> to an instance of <see cref="Country"/>.
        /// </summary>
        /// <param name="dtos"></param>
        /// <returns></returns>
        public static List<Country> ToEntities(this IEnumerable<CountryDTO> dtos)
        {
            if (dtos == null) return null;

            return dtos.Select(e => e.ToEntity()).ToList();
        }

        /// <summary>
        /// Converts each instance of <see cref="Country"/> to an instance of <see cref="CountryDTO"/>.
        /// </summary>
        /// <param name="entities"></param>
        /// <returns></returns>
        public static List<CountryDTO> ToDTOs(this IEnumerable<Country> entities)
        {
            if (entities == null) return null;

            return entities.Select(e => e.ToDTO()).ToList();
        }

    }
}
