//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.2 (entitiestodtos.codeplex.com).
//     Timestamp: 2016/02/22 - 20:58:47
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;
using System.Linq;
using JobsInABA.BL.DTOs;
using JobsInABA.DAL.Entities;

namespace JobsInABA.BL.DTOs.Assemblers
{

    /// <summary>
    /// Assembler for <see cref="Email"/> and <see cref="EmailDTO"/>.
    /// </summary>
    public static partial class EmailAssembler
    {
        /// <summary>
        /// Invoked when <see cref="ToDTO"/> operation is about to return.
        /// </summary>
        /// <param name="dto"><see cref="EmailDTO"/> converted from <see cref="Email"/>.</param>
        static partial void OnDTO(this Email entity, EmailDTO dto);

        /// <summary>
        /// Invoked when <see cref="ToEntity"/> operation is about to return.
        /// </summary>
        /// <param name="entity"><see cref="Email"/> converted from <see cref="EmailDTO"/>.</param>
        static partial void OnEntity(this EmailDTO dto, Email entity);

        /// <summary>
        /// Converts this instance of <see cref="EmailDTO"/> to an instance of <see cref="Email"/>.
        /// </summary>
        /// <param name="dto"><see cref="EmailDTO"/> to convert.</param>
        public static Email ToEntity(this EmailDTO dto)
        {
            if (dto == null) return null;

            var entity = new Email();

            entity.EmailID = dto.EmailID;
            entity.Address = dto.Address;
            entity.EmailTypeID = dto.EmailTypeID;

            dto.OnEntity(entity);

            return entity;
        }

        /// <summary>
        /// Converts this instance of <see cref="Email"/> to an instance of <see cref="EmailDTO"/>.
        /// </summary>
        /// <param name="entity"><see cref="Email"/> to convert.</param>
        public static EmailDTO ToDTO(this Email entity)
        {
            if (entity == null) return null;

            var dto = new EmailDTO();

            dto.EmailID = entity.EmailID;
            dto.Address = entity.Address;
            dto.EmailTypeID = entity.EmailTypeID;

            entity.OnDTO(dto);

            return dto;
        }

        /// <summary>
        /// Converts each instance of <see cref="EmailDTO"/> to an instance of <see cref="Email"/>.
        /// </summary>
        /// <param name="dtos"></param>
        /// <returns></returns>
        public static List<Email> ToEntities(this IEnumerable<EmailDTO> dtos)
        {
            if (dtos == null) return null;

            return dtos.Select(e => e.ToEntity()).ToList();
        }

        /// <summary>
        /// Converts each instance of <see cref="Email"/> to an instance of <see cref="EmailDTO"/>.
        /// </summary>
        /// <param name="entities"></param>
        /// <returns></returns>
        public static List<EmailDTO> ToDTOs(this IEnumerable<Email> entities)
        {
            if (entities == null) return null;

            return entities.Select(e => e.ToDTO()).ToList();
        }

    }
}
