//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.2 (entitiestodtos.codeplex.com).
//     Timestamp: 2016/02/22 - 20:58:49
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;
using System.Linq;
using JobsInABA.BL.DTOs;
using JobsInABA.DAL.Entities;

namespace JobsInABA.BL.DTOs.Assemblers
{

    /// <summary>
    /// Assembler for <see cref="Service"/> and <see cref="ServiceDTO"/>.
    /// </summary>
    public static partial class ServiceAssembler
    {
        /// <summary>
        /// Invoked when <see cref="ToDTO"/> operation is about to return.
        /// </summary>
        /// <param name="dto"><see cref="ServiceDTO"/> converted from <see cref="Service"/>.</param>
        static partial void OnDTO(this Service entity, ServiceDTO dto);

        /// <summary>
        /// Invoked when <see cref="ToEntity"/> operation is about to return.
        /// </summary>
        /// <param name="entity"><see cref="Service"/> converted from <see cref="ServiceDTO"/>.</param>
        static partial void OnEntity(this ServiceDTO dto, Service entity);

        /// <summary>
        /// Converts this instance of <see cref="ServiceDTO"/> to an instance of <see cref="Service"/>.
        /// </summary>
        /// <param name="dto"><see cref="ServiceDTO"/> to convert.</param>
        public static Service ToEntity(this ServiceDTO dto)
        {
            if (dto == null) return null;

            var entity = new Service();

            entity.ServiceID = dto.ServiceID;
            entity.Name = dto.Name;
            entity.BusinessID = dto.BusinessID;

            dto.OnEntity(entity);

            return entity;
        }

        /// <summary>
        /// Converts this instance of <see cref="Service"/> to an instance of <see cref="ServiceDTO"/>.
        /// </summary>
        /// <param name="entity"><see cref="Service"/> to convert.</param>
        public static ServiceDTO ToDTO(this Service entity)
        {
            if (entity == null) return null;

            var dto = new ServiceDTO();

            dto.ServiceID = entity.ServiceID;
            dto.Name = entity.Name;
            dto.BusinessID = entity.BusinessID;

            entity.OnDTO(dto);

            return dto;
        }

        /// <summary>
        /// Converts each instance of <see cref="ServiceDTO"/> to an instance of <see cref="Service"/>.
        /// </summary>
        /// <param name="dtos"></param>
        /// <returns></returns>
        public static List<Service> ToEntities(this IEnumerable<ServiceDTO> dtos)
        {
            if (dtos == null) return null;

            return dtos.Select(e => e.ToEntity()).ToList();
        }

        /// <summary>
        /// Converts each instance of <see cref="Service"/> to an instance of <see cref="ServiceDTO"/>.
        /// </summary>
        /// <param name="entities"></param>
        /// <returns></returns>
        public static List<ServiceDTO> ToDTOs(this IEnumerable<Service> entities)
        {
            if (entities == null) return null;

            return entities.Select(e => e.ToDTO()).ToList();
        }

    }
}
