//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.2 (entitiestodtos.codeplex.com).
//     Timestamp: 2016/02/22 - 20:58:49
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;
using System.Linq;
using JobsInABA.BL.DTOs;
using JobsInABA.DAL.Entities;

namespace JobsInABA.BL.DTOs.Assemblers
{

    /// <summary>
    /// Assembler for <see cref="UserAddress"/> and <see cref="UserAddressDTO"/>.
    /// </summary>
    public static partial class UserAddressAssembler
    {
        /// <summary>
        /// Invoked when <see cref="ToDTO"/> operation is about to return.
        /// </summary>
        /// <param name="dto"><see cref="UserAddressDTO"/> converted from <see cref="UserAddress"/>.</param>
        static partial void OnDTO(this UserAddress entity, UserAddressDTO dto);

        /// <summary>
        /// Invoked when <see cref="ToEntity"/> operation is about to return.
        /// </summary>
        /// <param name="entity"><see cref="UserAddress"/> converted from <see cref="UserAddressDTO"/>.</param>
        static partial void OnEntity(this UserAddressDTO dto, UserAddress entity);

        /// <summary>
        /// Converts this instance of <see cref="UserAddressDTO"/> to an instance of <see cref="UserAddress"/>.
        /// </summary>
        /// <param name="dto"><see cref="UserAddressDTO"/> to convert.</param>
        public static UserAddress ToEntity(this UserAddressDTO dto)
        {
            if (dto == null) return null;

            var entity = new UserAddress();

            entity.UserAddressID = dto.UserAddressID;
            entity.UserID = dto.UserID;
            entity.AddressID = dto.AddressID;
            entity.IsPrimary = dto.IsPrimary;

            dto.OnEntity(entity);

            return entity;
        }

        /// <summary>
        /// Converts this instance of <see cref="UserAddress"/> to an instance of <see cref="UserAddressDTO"/>.
        /// </summary>
        /// <param name="entity"><see cref="UserAddress"/> to convert.</param>
        public static UserAddressDTO ToDTO(this UserAddress entity)
        {
            if (entity == null) return null;

            var dto = new UserAddressDTO();

            dto.UserAddressID = entity.UserAddressID;
            dto.UserID = entity.UserID;
            dto.AddressID = entity.AddressID;
            dto.IsPrimary = entity.IsPrimary;

            entity.OnDTO(dto);

            return dto;
        }

        /// <summary>
        /// Converts each instance of <see cref="UserAddressDTO"/> to an instance of <see cref="UserAddress"/>.
        /// </summary>
        /// <param name="dtos"></param>
        /// <returns></returns>
        public static List<UserAddress> ToEntities(this IEnumerable<UserAddressDTO> dtos)
        {
            if (dtos == null) return null;

            return dtos.Select(e => e.ToEntity()).ToList();
        }

        /// <summary>
        /// Converts each instance of <see cref="UserAddress"/> to an instance of <see cref="UserAddressDTO"/>.
        /// </summary>
        /// <param name="entities"></param>
        /// <returns></returns>
        public static List<UserAddressDTO> ToDTOs(this IEnumerable<UserAddress> entities)
        {
            if (entities == null) return null;

            return entities.Select(e => e.ToDTO()).ToList();
        }

    }
}
