//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.2 (entitiestodtos.codeplex.com).
//     Timestamp: 2016/02/22 - 20:58:50
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;
using System.Linq;
using JobsInABA.BL.DTOs;
using JobsInABA.DAL.Entities;

namespace JobsInABA.BL.DTOs.Assemblers
{

    /// <summary>
    /// Assembler for <see cref="UserRole"/> and <see cref="UserRoleDTO"/>.
    /// </summary>
    public static partial class UserRoleAssembler
    {
        /// <summary>
        /// Invoked when <see cref="ToDTO"/> operation is about to return.
        /// </summary>
        /// <param name="dto"><see cref="UserRoleDTO"/> converted from <see cref="UserRole"/>.</param>
        static partial void OnDTO(this UserRole entity, UserRoleDTO dto);

        /// <summary>
        /// Invoked when <see cref="ToEntity"/> operation is about to return.
        /// </summary>
        /// <param name="entity"><see cref="UserRole"/> converted from <see cref="UserRoleDTO"/>.</param>
        static partial void OnEntity(this UserRoleDTO dto, UserRole entity);

        /// <summary>
        /// Converts this instance of <see cref="UserRoleDTO"/> to an instance of <see cref="UserRole"/>.
        /// </summary>
        /// <param name="dto"><see cref="UserRoleDTO"/> to convert.</param>
        public static UserRole ToEntity(this UserRoleDTO dto)
        {
            if (dto == null) return null;

            var entity = new UserRole();

            entity.UserRoleID = dto.UserRoleID;
            entity.UserID = dto.UserID;
            entity.RoleID = dto.RoleID;

            dto.OnEntity(entity);

            return entity;
        }

        /// <summary>
        /// Converts this instance of <see cref="UserRole"/> to an instance of <see cref="UserRoleDTO"/>.
        /// </summary>
        /// <param name="entity"><see cref="UserRole"/> to convert.</param>
        public static UserRoleDTO ToDTO(this UserRole entity)
        {
            if (entity == null) return null;

            var dto = new UserRoleDTO();

            dto.UserRoleID = entity.UserRoleID;
            dto.UserID = entity.UserID;
            dto.RoleID = entity.RoleID;

            entity.OnDTO(dto);

            return dto;
        }

        /// <summary>
        /// Converts each instance of <see cref="UserRoleDTO"/> to an instance of <see cref="UserRole"/>.
        /// </summary>
        /// <param name="dtos"></param>
        /// <returns></returns>
        public static List<UserRole> ToEntities(this IEnumerable<UserRoleDTO> dtos)
        {
            if (dtos == null) return null;

            return dtos.Select(e => e.ToEntity()).ToList();
        }

        /// <summary>
        /// Converts each instance of <see cref="UserRole"/> to an instance of <see cref="UserRoleDTO"/>.
        /// </summary>
        /// <param name="entities"></param>
        /// <returns></returns>
        public static List<UserRoleDTO> ToDTOs(this IEnumerable<UserRole> entities)
        {
            if (entities == null) return null;

            return entities.Select(e => e.ToDTO()).ToList();
        }

    }
}
