//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.2 (entitiestodtos.codeplex.com).
//     Timestamp: 2016/02/22 - 20:58:49
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;
using System.Linq;
using JobsInABA.BL.DTOs;
using JobsInABA.DAL.Entities;

namespace JobsInABA.BL.DTOs.Assemblers
{

    /// <summary>
    /// Assembler for <see cref="UserEmail"/> and <see cref="UserEmailDTO"/>.
    /// </summary>
    public static partial class UserEmailAssembler
    {
        /// <summary>
        /// Invoked when <see cref="ToDTO"/> operation is about to return.
        /// </summary>
        /// <param name="dto"><see cref="UserEmailDTO"/> converted from <see cref="UserEmail"/>.</param>
        static partial void OnDTO(this UserEmail entity, UserEmailDTO dto);

        /// <summary>
        /// Invoked when <see cref="ToEntity"/> operation is about to return.
        /// </summary>
        /// <param name="entity"><see cref="UserEmail"/> converted from <see cref="UserEmailDTO"/>.</param>
        static partial void OnEntity(this UserEmailDTO dto, UserEmail entity);

        /// <summary>
        /// Converts this instance of <see cref="UserEmailDTO"/> to an instance of <see cref="UserEmail"/>.
        /// </summary>
        /// <param name="dto"><see cref="UserEmailDTO"/> to convert.</param>
        public static UserEmail ToEntity(this UserEmailDTO dto)
        {
            if (dto == null) return null;

            var entity = new UserEmail();

            entity.UserEmailID = dto.UserEmailID;
            entity.UserID = dto.UserID;
            entity.EmailID = dto.EmailID;
            entity.IsPrimary = dto.IsPrimary;

            dto.OnEntity(entity);

            return entity;
        }

        /// <summary>
        /// Converts this instance of <see cref="UserEmail"/> to an instance of <see cref="UserEmailDTO"/>.
        /// </summary>
        /// <param name="entity"><see cref="UserEmail"/> to convert.</param>
        public static UserEmailDTO ToDTO(this UserEmail entity)
        {
            if (entity == null) return null;

            var dto = new UserEmailDTO();

            dto.UserEmailID = entity.UserEmailID;
            dto.UserID = entity.UserID;
            dto.EmailID = entity.EmailID;
            dto.IsPrimary = entity.IsPrimary;

            entity.OnDTO(dto);

            return dto;
        }

        /// <summary>
        /// Converts each instance of <see cref="UserEmailDTO"/> to an instance of <see cref="UserEmail"/>.
        /// </summary>
        /// <param name="dtos"></param>
        /// <returns></returns>
        public static List<UserEmail> ToEntities(this IEnumerable<UserEmailDTO> dtos)
        {
            if (dtos == null) return null;

            return dtos.Select(e => e.ToEntity()).ToList();
        }

        /// <summary>
        /// Converts each instance of <see cref="UserEmail"/> to an instance of <see cref="UserEmailDTO"/>.
        /// </summary>
        /// <param name="entities"></param>
        /// <returns></returns>
        public static List<UserEmailDTO> ToDTOs(this IEnumerable<UserEmail> entities)
        {
            if (entities == null) return null;

            return entities.Select(e => e.ToDTO()).ToList();
        }

    }
}
