//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.2 (entitiestodtos.codeplex.com).
//     Timestamp: 2016/02/22 - 20:58:28
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;

namespace JobsInABA.BL.DTOs
{
    [DataContract()]
    public partial class AchievementDTO
    {
        [DataMember()]
        public Int32 AchievementID { get; set; }

        [DataMember()]
        public String Name { get; set; }

        [DataMember()]
        public Nullable<DateTime> Date { get; set; }

        [DataMember()]
        public Nullable<Int32> UserID { get; set; }

        [DataMember()]
        public Nullable<Int32> BusinessID { get; set; }

        [DataMember()]
        public BusinessDTO Business { get; set; }

        [DataMember()]
        public Int32 Business_BusinessID { get; set; }

        [DataMember()]
        public UserDTO User { get; set; }

        [DataMember()]
        public Int32 User_UserID { get; set; }

        public AchievementDTO()
        {
        }

        public AchievementDTO(Int32 achievementID, String name, Nullable<DateTime> date, Nullable<Int32> userID, Nullable<Int32> businessID, Int32 business_BusinessID, Int32 user_UserID)
        {
            this.AchievementID = achievementID;
            this.Name = name;
            this.Date = date;
            this.UserID = userID;
            this.BusinessID = businessID;
            this.Business_BusinessID = business_BusinessID;
            this.User_UserID = user_UserID;
        }
    }
}
