//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.2 (entitiestodtos.codeplex.com).
//     Timestamp: 2016/02/22 - 20:58:31
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;

namespace JobsInABA.BL.DTOs
{
    [DataContract()]
    public partial class BusinessImageDTO
    {
        [DataMember()]
        public Int32 BusinessImageID { get; set; }

        [DataMember()]
        public Int32 BusinessID { get; set; }

        [DataMember()]
        public Int32 ImageID { get; set; }

        [DataMember()]
        public Boolean IsPrimary { get; set; }

        [DataMember()]
        public Int32 Business_BusinessID { get; set; }

        [DataMember()]
        public ImageDTO Image { get; set; }

        [DataMember()]
        public Int32 Image_ImageID { get; set; }

        public BusinessImageDTO()
        {
        }

        public BusinessImageDTO(Int32 businessImageID, Int32 businessID, Int32 imageID, Boolean isPrimary, Int32 business_BusinessID, Int32 image_ImageID)
        {
			this.BusinessImageID = businessImageID;
			this.BusinessID = businessID;
			this.ImageID = imageID;
			this.IsPrimary = isPrimary;
			this.Business_BusinessID = business_BusinessID;
			this.Image_ImageID = image_ImageID;
        }
    }
}
