//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.2 (entitiestodtos.codeplex.com).
//     Timestamp: 2016/02/22 - 20:58:32
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;

namespace JobsInABA.BL.DTOs
{
    [DataContract()]
    public partial class BusinessUserMapDTO
    {
        [DataMember()]
        public Int32 BusinessUserMapID { get; set; }

        [DataMember()]
        public Int32 BusinessID { get; set; }

        [DataMember()]
        public Int32 UserID { get; set; }

        [DataMember()]
        public Boolean IsOwner { get; set; }

        [DataMember()]
        public Nullable<Int32> BusinessUserTypeID { get; set; }

        [DataMember()]
        public Int32 Business_BusinessID { get; set; }

        [DataMember()]
        public Int32 TypeCode_TypeCodeID { get; set; }

        [DataMember()]
        public UserDTO User { get; set; }

        [DataMember()]
        public Int32 User_UserID { get; set; }

        public BusinessUserMapDTO()
        {
        }

        public BusinessUserMapDTO(Int32 businessUserMapID, Int32 businessID, Int32 userID, Boolean isOwner, Nullable<Int32> businessUserTypeID, Int32 business_BusinessID, Int32 typeCode_TypeCodeID, Int32 user_UserID)
        {
			this.BusinessUserMapID = businessUserMapID;
			this.BusinessID = businessID;
			this.UserID = userID;
			this.IsOwner = isOwner;
			this.BusinessUserTypeID = businessUserTypeID;
			this.Business_BusinessID = business_BusinessID;
			this.TypeCode_TypeCodeID = typeCode_TypeCodeID;
			this.User_UserID = user_UserID;
        }
    }
}
