//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.2 (entitiestodtos.codeplex.com).
//     Timestamp: 2016/02/22 - 20:58:30
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;

namespace JobsInABA.BL.DTOs
{
    [DataContract()]
    public partial class BusinessEmailDTO
    {
        [DataMember()]
        public Int32 BusinessEmailID { get; set; }

        [DataMember()]
        public Int32 BusinessID { get; set; }

        [DataMember()]
        public Int32 EmailID { get; set; }

        [DataMember()]
        public Boolean IsPrimary { get; set; }

        [DataMember()]
        public Int32 Business_BusinessID { get; set; }

        [DataMember()]
        public EmailDTO Email { get; set; }

        [DataMember()]
        public Int32 Email_EmailID { get; set; }

        public BusinessEmailDTO()
        {
        }

        public BusinessEmailDTO(Int32 businessEmailID, Int32 businessID, Int32 emailID, Boolean isPrimary, Int32 business_BusinessID, Int32 email_EmailID)
        {
			this.BusinessEmailID = businessEmailID;
			this.BusinessID = businessID;
			this.EmailID = emailID;
			this.IsPrimary = isPrimary;
			this.Business_BusinessID = business_BusinessID;
			this.Email_EmailID = email_EmailID;
        }
    }
}
