//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.2 (entitiestodtos.codeplex.com).
//     Timestamp: 2016/02/22 - 20:58:29
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;

namespace JobsInABA.BL.DTOs
{
    [DataContract()]
    public partial class BusinessAddressDTO
    {
        [DataMember()]
        public Int32 BusinessAddressID { get; set; }

        [DataMember()]
        public Int32 BusinessID { get; set; }

        [DataMember()]
        public Int32 AddressID { get; set; }

        [DataMember()]
        public Boolean IsPrimary { get; set; }

        [DataMember()]
        public AddressDTO Addres { get; set; }

        [DataMember()]
        public Int32 Address_AddressID { get; set; }

        [DataMember()]
        public Int32 Business_BusinessID { get; set; }

        public BusinessAddressDTO()
        {
        }

        public BusinessAddressDTO(Int32 businessAddressID, Int32 businessID, Int32 addressID, Boolean isPrimary, Int32 address_AddressID, Int32 business_BusinessID)
        {
			this.BusinessAddressID = businessAddressID;
			this.BusinessID = businessID;
			this.AddressID = addressID;
			this.IsPrimary = isPrimary;
			this.Address_AddressID = address_AddressID;
			this.Business_BusinessID = business_BusinessID;
        }
    }
}
