//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.2 (entitiestodtos.codeplex.com).
//     Timestamp: 2016/02/22 - 20:58:33
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;

namespace JobsInABA.BL.DTOs
{
    [DataContract()]
    public partial class ClassTypeDTO
    {
        [DataMember()]
        public Int32 ClassTypeID { get; set; }

        [DataMember()]
        public String Name { get; set; }

        [DataMember()]
        public String Code { get; set; }

        [DataMember()]
        public String Description { get; set; }

        [DataMember()]
        public List<Int32> TypeCodes_TypeCodeID { get; set; }

        public ClassTypeDTO()
        {
        }

        public ClassTypeDTO(Int32 classTypeID, String name, String code, String description, List<Int32> typeCodes_TypeCodeID)
        {
			this.ClassTypeID = classTypeID;
			this.Name = name;
			this.Code = code;
			this.Description = description;
			this.TypeCodes_TypeCodeID = typeCodes_TypeCodeID;
        }
    }
}
