//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.2 (entitiestodtos.codeplex.com).
//     Timestamp: 2016/02/22 - 20:58:33
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;

namespace JobsInABA.BL.DTOs
{
    [DataContract()]
    public partial class CountryDTO
    {
        [DataMember()]
        public Int32 CountryID { get; set; }

        [DataMember()]
        public String Name { get; set; }

        [DataMember()]
        public String Abbreviation { get; set; }

        [DataMember()]
        public String Code { get; set; }

        [DataMember()]
        public String PhoneCode { get; set; }

        [DataMember()]
        public List<Int32> Addresses_AddressID { get; set; }

        public CountryDTO()
        {
        }

        public CountryDTO(Int32 countryID, String name, String abbreviation, String code, String phoneCode, List<Int32> addresses_AddressID)
        {
			this.CountryID = countryID;
			this.Name = name;
			this.Abbreviation = abbreviation;
			this.Code = code;
			this.PhoneCode = phoneCode;
			this.Addresses_AddressID = addresses_AddressID;
        }
    }
}
