//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.2 (entitiestodtos.codeplex.com).
//     Timestamp: 2016/02/22 - 20:58:33
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;

namespace JobsInABA.BL.DTOs
{
    [DataContract()]
    public partial class EducationDTO
    {
        [DataMember()]
        public Int32 EducationID { get; set; }

        [DataMember()]
        public Int32 UserID { get; set; }

        [DataMember()]
        public String InstituteName { get; set; }

        [DataMember()]
        public String Degree { get; set; }

        [DataMember()]
        public String Description { get; set; }

        [DataMember()]
        public Nullable<DateTime> StartDate { get; set; }

        [DataMember()]
        public Nullable<DateTime> EndDate { get; set; }

        [DataMember()]
        public Nullable<Boolean> IsActive { get; set; }

        [DataMember()]
        public Nullable<Boolean> IsDelete { get; set; }

        [DataMember()]
        public UserDTO User { get; set; }

        [DataMember()]
        public Int32 User_UserID { get; set; }

        public EducationDTO()
        {
        }

        public EducationDTO(Int32 educationID, Int32 userID, String instituteName, String degree, String description, Nullable<DateTime> startDate, Nullable<DateTime> endDate, Nullable<Boolean> isActive, Nullable<Boolean> isDelete, Int32 user_UserID)
        {
			this.EducationID = educationID;
			this.UserID = userID;
			this.InstituteName = instituteName;
			this.Degree = degree;
			this.Description = description;
			this.StartDate = startDate;
			this.EndDate = endDate;
			this.IsActive = isActive;
			this.IsDelete = isDelete;
			this.User_UserID = user_UserID;
        }
    }
}
