//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.2 (entitiestodtos.codeplex.com).
//     Timestamp: 2016/02/22 - 20:58:34
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;

namespace JobsInABA.BL.DTOs
{
    [DataContract()]
    public partial class EmailDTO
    {
        [DataMember()]
        public Int32 EmailID { get; set; }

        [DataMember()]
        public String Address { get; set; }

        [DataMember()]
        public Nullable<Int32> EmailTypeID { get; set; }

        [DataMember()]
        public List<Int32> BusinessEmails_BusinessEmailID { get; set; }

        [DataMember()]
        public TypeCodeDTO TypeCode { get; set; }

        [DataMember()]
        public Int32 TypeCode_TypeCodeID { get; set; }

        [DataMember()]
        public List<Int32> UserEmails_UserEmailID { get; set; }

        public EmailDTO()
        {
        }

        public EmailDTO(Int32 emailID, String address, Nullable<Int32> emailTypeID, List<Int32> businessEmails_BusinessEmailID, Int32 typeCode_TypeCodeID, List<Int32> userEmails_UserEmailID)
        {
			this.EmailID = emailID;
			this.Address = address;
			this.EmailTypeID = emailTypeID;
			this.BusinessEmails_BusinessEmailID = businessEmails_BusinessEmailID;
			this.TypeCode_TypeCodeID = typeCode_TypeCodeID;
			this.UserEmails_UserEmailID = userEmails_UserEmailID;
        }
    }
}
