//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.2 (entitiestodtos.codeplex.com).
//     Timestamp: 2016/02/22 - 20:58:35
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;

namespace JobsInABA.BL.DTOs
{
    [DataContract()]
    public partial class ImageDTO
    {
        [DataMember()]
        public Int32 ImageID { get; set; }

        [DataMember()]
        public String Name { get; set; }

        [DataMember()]
        public Int32 ImageTypeID { get; set; }

        [DataMember()]
        public String ImageExtension { get; set; }

        [DataMember()]
        public List<Int32> BusinessImages_BusinessImageID { get; set; }

        [DataMember()]
        public Int32 TypeCode_TypeCodeID { get; set; }

        [DataMember()]
        public List<Int32> UserImages_UserImageID { get; set; }

        public ImageDTO()
        {
        }

        public ImageDTO(Int32 imageID, String name, Int32 imageTypeID, String imageExtension, List<Int32> businessImages_BusinessImageID, Int32 typeCode_TypeCodeID, List<Int32> userImages_UserImageID)
        {
			this.ImageID = imageID;
			this.Name = name;
			this.ImageTypeID = imageTypeID;
			this.ImageExtension = imageExtension;
			this.BusinessImages_BusinessImageID = businessImages_BusinessImageID;
			this.TypeCode_TypeCodeID = typeCode_TypeCodeID;
			this.UserImages_UserImageID = userImages_UserImageID;
        }
    }
}
