//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.2 (entitiestodtos.codeplex.com).
//     Timestamp: 2016/02/22 - 20:58:36
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;

namespace JobsInABA.BL.DTOs
{
    [DataContract()]
    public partial class JobApplicationStateDTO
    {
        [DataMember()]
        public Int32 JobApplicationStateID { get; set; }

        [DataMember()]
        public Int32 JobApplicationID { get; set; }

        [DataMember()]
        public Int32 JobApplicationStatusID { get; set; }

        [DataMember()]
        public DateTime insdt { get; set; }

        [DataMember()]
        public Int32 insuser { get; set; }

        [DataMember()]
        public Int32 JobApplication_JobApplicationID { get; set; }

        [DataMember()]
        public Int32 TypeCode_TypeCodeID { get; set; }

        public JobApplicationStateDTO()
        {
        }

        public JobApplicationStateDTO(Int32 jobApplicationStateID, Int32 jobApplicationID, Int32 jobApplicationStatusID, DateTime insdt, Int32 insuser, Int32 jobApplication_JobApplicationID, Int32 typeCode_TypeCodeID)
        {
			this.JobApplicationStateID = jobApplicationStateID;
			this.JobApplicationID = jobApplicationID;
			this.JobApplicationStatusID = jobApplicationStatusID;
			this.insdt = insdt;
			this.insuser = insuser;
			this.JobApplication_JobApplicationID = jobApplication_JobApplicationID;
			this.TypeCode_TypeCodeID = typeCode_TypeCodeID;
        }
    }
}
