//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.2 (entitiestodtos.codeplex.com).
//     Timestamp: 2016/02/22 - 20:58:36
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;

namespace JobsInABA.BL.DTOs
{
    [DataContract()]
    public partial class JobApplicationDTO
    {
        [DataMember()]
        public Int32 JobApplicationID { get; set; }

        [DataMember()]
        public Int32 JobID { get; set; }

        [DataMember()]
        public Int32 ApplicantUserID { get; set; }

        [DataMember()]
        public DateTime ApplicationDate { get; set; }

        [DataMember()]
        public Int32 Job_JobID { get; set; }

        [DataMember()]
        public UserDTO User { get; set; }

        [DataMember()]
        public Int32 User_UserID { get; set; }

        [DataMember()]
        public List<Int32> JobApplicationStates_JobApplicationStateID { get; set; }

        public JobApplicationDTO()
        {
        }

        public JobApplicationDTO(Int32 jobApplicationID, Int32 jobID, Int32 applicantUserID, DateTime applicationDate, Int32 job_JobID, Int32 user_UserID, List<Int32> jobApplicationStates_JobApplicationStateID)
        {
			this.JobApplicationID = jobApplicationID;
			this.JobID = jobID;
			this.ApplicantUserID = applicantUserID;
			this.ApplicationDate = applicationDate;
			this.Job_JobID = job_JobID;
			this.User_UserID = user_UserID;
			this.JobApplicationStates_JobApplicationStateID = jobApplicationStates_JobApplicationStateID;
        }
    }
}
