//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.2 (entitiestodtos.codeplex.com).
//     Timestamp: 2016/02/22 - 20:58:38
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;

namespace JobsInABA.BL.DTOs
{
    [DataContract()]
    public partial class LanguageDTO
    {
        [DataMember()]
        public Int32 LanguageID { get; set; }

        [DataMember()]
        public String LanguageName { get; set; }

        [DataMember()]
        public Int32 UserID { get; set; }

        [DataMember()]
        public UserDTO User { get; set; }

        [DataMember()]
        public Int32 User_UserID { get; set; }

        public LanguageDTO()
        {
        }

        public LanguageDTO(Int32 languageID, String languageName, Int32 userID, Int32 user_UserID)
        {
            this.LanguageID = languageID;
            this.LanguageName = languageName;
            this.UserID = userID;
            this.User_UserID = user_UserID;
        }
    }
}
