//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.2 (entitiestodtos.codeplex.com).
//     Timestamp: 2016/02/22 - 20:58:39
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;

namespace JobsInABA.BL.DTOs
{
    [DataContract()]
    public partial class ServiceDTO
    {
        [DataMember()]
        public Int32 ServiceID { get; set; }

        [DataMember()]
        public String Name { get; set; }

        [DataMember()]
        public Int32 BusinessID { get; set; }

        [DataMember()]
        public Int32 Business_BusinessID { get; set; }

        public ServiceDTO()
        {
        }

        public ServiceDTO(Int32 serviceID, String name, Int32 businessID, Int32 business_BusinessID)
        {
			this.ServiceID = serviceID;
			this.Name = name;
			this.BusinessID = businessID;
			this.Business_BusinessID = business_BusinessID;
        }
    }
}
