//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.2 (entitiestodtos.codeplex.com).
//     Timestamp: 2016/02/22 - 20:58:39
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;

namespace JobsInABA.BL.DTOs
{
    [DataContract()]
    public partial class SkillDTO
    {
        [DataMember()]
        public Int32 SkillID { get; set; }

        [DataMember()]
        public String Skill1 { get; set; }

        [DataMember()]
        public Int32 UserID { get; set; }

        [DataMember()]
        public UserDTO User { get; set; }

        [DataMember()]
        public Int32 User_UserID { get; set; }

        public SkillDTO()
        {
        }

        public SkillDTO(Int32 skillID, String skill1, Int32 userID, Int32 user_UserID)
        {
			this.SkillID = skillID;
			this.Skill1 = skill1;
			this.UserID = userID;
			this.User_UserID = user_UserID;
        }
    }
}
