/*
Project: Jobs In ABA
Authoer: Ghanshyam Bhalala
Date Created: 2015-12-04

*/
//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.2 (entitiestodtos.codeplex.com).
//     Timestamp: 2016/01/01 - 02:55:28
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;

namespace JobsInABA.DTOs
{
    [DataContract()]
    public partial class sysdiagramDTO
    {
        [DataMember()]
        public String name { get; set; }

        [DataMember()]
        public Int32 principal_id { get; set; }

        [DataMember()]
        public Int32 diagram_id { get; set; }

        [DataMember()]
        public Nullable<Int32> version { get; set; }

        [DataMember()]
        public Byte[] definition { get; set; }

        public sysdiagramDTO()
        {
        }

        public sysdiagramDTO(String name, Int32 principal_id, Int32 diagram_id, Nullable<Int32> version, Byte[] definition)
        {
			this.name = name;
			this.principal_id = principal_id;
			this.diagram_id = diagram_id;
			this.version = version;
			this.definition = definition;
        }
    }
}
