//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.2 (entitiestodtos.codeplex.com).
//     Timestamp: 2016/02/22 - 20:58:42
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;

namespace JobsInABA.BL.DTOs
{
    [DataContract()]
    public partial class UserImageDTO
    {
        [DataMember()]
        public Int32 UserImageID { get; set; }

        [DataMember()]
        public Int32 UserID { get; set; }

        [DataMember()]
        public Int32 ImageID { get; set; }

        [DataMember()]
        public Boolean IsPrimary { get; set; }

        [DataMember()]
        public ImageDTO Image { get; set; }

        [DataMember()]
        public Int32 Image_ImageID { get; set; }

        [DataMember()]
        public Int32 User_UserID { get; set; }

        public UserImageDTO()
        {
        }

        public UserImageDTO(Int32 userImageID, Int32 userID, Int32 imageID, Boolean isPrimary, Int32 image_ImageID, Int32 user_UserID)
        {
			this.UserImageID = userImageID;
			this.UserID = userID;
			this.ImageID = imageID;
			this.IsPrimary = isPrimary;
			this.Image_ImageID = image_ImageID;
			this.User_UserID = user_UserID;
        }
    }
}
