//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.2 (entitiestodtos.codeplex.com).
//     Timestamp: 2016/02/22 - 20:58:41
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;

namespace JobsInABA.BL.DTOs
{
    [DataContract()]
    public partial class UserAddressDTO
    {
        [DataMember()]
        public Int32 UserAddressID { get; set; }

        [DataMember()]
        public Int32 UserID { get; set; }

        [DataMember()]
        public Int32 AddressID { get; set; }

        [DataMember()]
        public Boolean IsPrimary { get; set; }

        [DataMember()]
        public AddressDTO Address { get; set; }

        [DataMember()]
        public Int32 Address_AddressID { get; set; }

        [DataMember()]
        public Int32 User_UserID { get; set; }

        public UserAddressDTO()
        {
        }

        public UserAddressDTO(Int32 userAddressID, Int32 userID, Int32 addressID, Boolean isPrimary, Int32 address_AddressID, Int32 user_UserID)
        {
			this.UserAddressID = userAddressID;
			this.UserID = userID;
			this.AddressID = addressID;
			this.IsPrimary = isPrimary;
			this.Address_AddressID = address_AddressID;
			this.User_UserID = user_UserID;
        }
    }
}
