//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.2 (entitiestodtos.codeplex.com).
//     Timestamp: 2016/02/22 - 20:58:43
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;

namespace JobsInABA.BL.DTOs
{
    [DataContract()]
    public partial class UserRoleDTO
    {
        [DataMember()]
        public Int32 UserRoleID { get; set; }

        [DataMember()]
        public Int32 UserID { get; set; }

        [DataMember()]
        public Int32 RoleID { get; set; }

        [DataMember()]
        public Int32 Role_RoleID { get; set; }

        [DataMember()]
        public Int32 User_UserID { get; set; }

        public UserRoleDTO()
        {
        }

        public UserRoleDTO(Int32 userRoleID, Int32 userID, Int32 roleID, Int32 role_RoleID, Int32 user_UserID)
        {
            this.UserRoleID = userRoleID;
            this.UserID = userID;
            this.RoleID = roleID;
            this.Role_RoleID = role_RoleID;
            this.User_UserID = user_UserID;
        }
    }
}
