//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JobsInABA.Component.AddressBook.ef
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClassType
    {
        public ClassType()
        {
            this.TypeCodes = new HashSet<TypeCode>();
        }
    
        public int ClassTypeID { get; set; }
        public string Name { get; set; }
        public string Code { get; set; }
        public string Description { get; set; }
    
        public virtual ICollection<TypeCode> TypeCodes { get; set; }
    }
}
